image: maven:3.3.9-jdk-8

cache:
    untracked: true

mybuild:
    stage: build
    script: 
      - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dmaven.test.failure.ignore=true -Dmaven.repo.local=/cache/maven.repo
    artifacts:
       paths:
        - */target/*.jar
       expire_in: 4 weeks
